### Login
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123!"
}

### Vehicles
GET http://127.0.0.1:8000/api/v1/vehicles
Authorization: Bearer {{token}}

### Dashboard
GET http://127.0.0.1:8000/api/v1/analytics/dashboard
Authorization: Bearer {{token}}

### Recommendation for task 1
GET http://127.0.0.1:8000/api/v1/recommendations/tasks/1/vehicles
Authorization: Bearer {{token}}
